/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:fe350919-b753-468f-be36-fe20aec8fd52",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_bhQWKEz7N",
    "aws_user_pools_web_client_id": "3a0ukvga60nk0ls8o67dif46dj",
    "oauth": {}
};


export default awsmobile;
